### ISSUE TITLE
Tests for text downloads fail.

### ISSUE THREAD

**Issue by mab-work** [DrumTechnologiesLtd/crocodoc-node#2]
The Crocodoc account I am using for testing does not have text download enabled, so the tests fail, and the implementation remains unproven.

**Comment by lakenen** [comment]
@mab-netdev I was able to run the tests on an account with text extraction enabled, and all the tests completed successfully.

**Comment by mab-work** [comment]
@camupod Thanks for verifying that.
Any chance of pasting / gisting spec reporter output which confirms that?
I'd be happier closing this issue with that as evidence.

**Comment by lakenen** [comment]
Here are the mocha test results showing all passing: https://gist.github.com/4693070

**Comment by mab-work** [comment]
Thanks Cameron!
